"""add created_at to task_metrics

Revision ID: 31e24b28b28e
Revises: 607ba58c3415
Create Date: 2026-09-08 13:33:36.731904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e24b28b28e'
down_revision: Union[str, Sequence[str], None] = '607ba58c3415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_metrics', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_metrics', 'created_at')
    # ### end Alembic commands ###
