"""add task owner to metrics

Revision ID: f3203d5fcbc2
Revises: 31e24b28b28e
Create Date: 2026-09-08 14:08:54.056653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3203d5fcbc2'
down_revision: Union[str, Sequence[str], None] = '31e24b28b28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_metrics', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_task_metrics_owner_id'), 'task_metrics', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_metrics_owner_id'), table_name='task_metrics')
    op.drop_column('task_metrics', 'owner_id')
    # ### end Alembic commands ###
