# Generated by Django 6.1.1 on 2026-09-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
